---
title: "Untitled"
author: "J. Beaulieu"
date: "January 18, 2017"
output: html_document
---

```{r setup}
knitr::opts_knit$set(root.dir = 'C:/Users/JBEAULIE/GitRepository/mulitResSurvey/ohio2016')
```

```{r results='hide', message=FALSE, warning=FALSE, echo=FALSE}

# For Jake Beaulieu.  Modify for your machine.

```

## DOT PLOTS

```{r echo=FALSE, warning=FALSE, fig.width=7, fig.height=3}
####################################################################################
### Item #4: Ordered dotplots of total CH4 emissions, TP, TN, and chla

# Highlight Harsha Lake (lake of interest) data with color
plotColor <- ifelse(meanVariance.c.lake.lu$Lake_Name == "William H Harsha Lake",
                    "red", "black")

# CH4 total emission rate
# Reset plotting order for CH4 total emissions
# "orderLake" is a function defined in the masterLibrary.R script
meanVariance.c.lake.lu$fLake_Name <- orderLake(meanVariance.c.lake.lu, 
                                               choice1 = "ch4.t")
ggplot(meanVariance.c.lake.lu,
       aes(ch4.trate.mg.h_Estimate, fLake_Name)) +
  geom_point(color = plotColor) +
  geom_errorbarh(aes(xmax = ch4.trate.mg.h_UCB95Pct, 
                     xmin = ch4.trate.mg.h_LCB95Pct), 
                 color = plotColor) +
  xlab(expression(CH[4]~emission~rate~(mg~ CH[4]~ m^{-2}~ hr^{-1}))) +
  theme(axis.title.y = element_blank()) +  # Eliminate x-axis title
  ggtitle(expression(Mean~CH[4]~emission~rate~
                       paste("(", "95% CI", ")", sep = "")))


# Chlorophyll 
meanVariance.c.lake.lu$fLake_Name <- orderLake(meanVariance.c.lake.lu, 
                                               choice1 = "chl")
ggplot(meanVariance.c.lake.lu,
       aes(chla_Estimate, fLake_Name)) +
  geom_point(color = plotColor) +
  geom_errorbarh(aes(xmax = chla_UCB95Pct, xmin = chla_LCB95Pct), color = plotColor) +
  xlab(expression(chl~a~paste("(", {mu}, "g ", L^{-1}, ")", sep = ""))) +
  theme(axis.title.y = element_blank())+
  ggtitle("Mean Chlorophyll a (95% CI)")


# TP 
# Reset plotting order to rank by TP
meanVariance.c.lake.lu$fLake_Name <- orderLake(meanVariance.c.lake.lu, choice1 = "TP")
ggplot(meanVariance.c.lake.lu,
       aes(tp_Estimate, fLake_Name)) +
  geom_point(color = plotColor) +
  geom_errorbarh(aes(xmax = tp_UCB95Pct, 
                     xmin = tp_LCB95Pct), 
                 color = plotColor) +
  xlab(expression(Total~Phosphorus~paste("(", {mu}, "g P ", L^{-1}, ")", sep = ""))) +   #NEED TO EDIT WITH UNITS
  theme(axis.title.y = element_blank()) +  # Eliminate x-axis title
  ggtitle("Mean TP (95% CI)")



# TN 
# Reset plotting order to rank by TN
meanVariance.c.lake.lu$fLake_Name <- orderLake(meanVariance.c.lake.lu, choice1 = "TN")
ggplot(meanVariance.c.lake.lu,
       aes(tn_Estimate, fLake_Name)) +
  geom_point(color = plotColor) +
  geom_errorbarh(aes(xmax = tn_UCB95Pct, 
                     xmin = tn_LCB95Pct), 
                 color = plotColor) +
  xlab(expression(Total~Nitrogen~paste("(", {mu}, "g N ", L^{-1}, ")", sep = ""))) +   #NEED TO EDIT WITH UNITS
  theme(axis.title.y = element_blank()) +  # Eliminate x-axis title
  ggtitle("Mean TN (95% CI)")




```

## Table

```{r warning=FALSE, echo=FALSE}
######################################################################
#### Item #5: Table of Water Quality Values by Site
## work in progress. Goal: produce a table for each lake with water quality and 
## GHG emissions info, including data that was not in the plots. Need to isolate
## the relevant data for each lake, rename the column headings, and add units

# dplyr package 
#"filter" command filters rows of interest. We're filtering the dataset for the 
# sampled sites at a given lake.
#"select" command selects the columns we want to show. The order they are listed 
#in the () is the order they will appear
actonTable <- filter(eqAreaData, Lake_Name == "Acton Lake", 
                     EvalStatus == "sampled") %>%
  select(siteID, LatSamp, LongSmp, wtrDpth,  #site identification  
         TNH4, TNO2.3, TN, TRP, TP,   #nutrient data
         chla_S, DO__L_S,  pH_S, SpCn__S, Tmp_C_S,  TrNTU_S) #shallow sonde

kable(actonTable,
      col.names = c("Site ID", "Latitude", "Longitude", "Site Depth (m)",
                    "NH4 (ugN/L)", "NO2 + NO3", "Total N (ugN/L)", "Total Reactive P",
                    "Total P", "Chl a (ug/L)", "Shallow DO (mg/L)", "Shallow pH",
                    "Shallow Specific Conductivity", "Shallow Temperature (C)", 
                    "Shallow Turbidity"))

```

