source("ohio2016/scriptsAndRmd/masterLibrary.R")
source("ohio2016/scriptsAndRmd/readSitesEqAreaData.R")
source("ohio2016/scriptsAndRmd/readLgr.R")
source("ohio2016/scriptsAndRmd/plotCleanLgr.R")
source("ohio2016/scriptsAndRmd/calculateEbullitionRate.R")
source("ohio2016/scriptsAndRmd/grtsWgtAdj.R")
source("ohio2016/scriptsAndRmd/calculateDiffusion.R")
source("ohio2016/scriptsAndRmd/grtsMeanVariance.R")
