# Pull in 'Final' models generated by running evalViPlots.R on VM.  Models were
# written to disk and copied to local repo via OneDrive.

# LOAD AND MODIFY DATA----------------
# Load models
load("ohio2016/output/cList.3.RData") # ~30sec
fMods <- cList.3 # 'fMods' for final models

# ggplot objects created on VM, then read in to EZTech system, aren't
# rendered on EZTech machine.  May be related to differences in R and 
# package versions between machines (?).  Will recreate those plot objects 
# (predPlot, RelInfPlot) here.

mPlots <- 
lapply(fMods, function(x) {
tmpData <- data.frame(resp = x$gbm$data$y, # observed values
                      isPreds = predict.gbm(x$gbm)) # predicted values

predPlot <- ggplot(tmpData, aes(resp, isPreds)) + 
  geom_point() +
  geom_abline(slope = 1, intercept = 0) +
  ylab("predicted") +
  xlab("obs") +
  xlim(range(c(tmpData$resp) , 
               tmpData$isPreds)) + # equal range x/y axis
  ylim(range(c(tmpData$resp) , 
             tmpData$isPreds)) + # equal range x/y axis
  ggtitle(paste(x$run.name, "\n",
                "mse_is =", round(x$mse[1,2], 2),
                "  mse_os =", round(x$mse[2,2], 2), "\n",
                "optTrees =", x$optTrees, "\n",
                "r2 =", x$rsq_is)) +
  theme(plot.title = element_text(size = 12))



## Relative influence plot
relInfDf <- x$gbm %>% summary(plotit = FALSE) %>% filter(rel.inf >= 5)
relInfPlot <- ggplot(relInfDf, aes(x = reorder(var, rel.inf), y=rel.inf)) + geom_bar(stat = "identity") +
  coord_flip() + ylab("Relative Influence (0-100)") + xlab("Variable") +
  ggtitle(x$run.name) +
  theme(plot.title = element_text(size = 10))

return(list("predPlot"=predPlot, "RelInfPlot"=relInfPlot))
}
)

# Now replace plots in list of final models (fMods) with new plots generated
# above.
for(i in seq_along(fMods)){
  fMods[[i]]$predPlot <- mPlots[[i]]$predPlot
  fMods[[i]]$RelInfPlot <- mPlots[[i]]$RelInfPlot
}

# SUMMARIZE MODEL RESULTS
# Print relative influence plots, prediction plots, and partial dependence plots
pdf("ohio2016/output/figures/gbm.final.pdf", paper = "a4r") # landscape orientation
for (i in 1:length(fMods)) {
  grid.arrange(fMods[[i]]$RelInfPlot, fMods[[i]]$predPlot, ncol = 2, nrow = 2) # use to put two plots per page
  print(fMods[[i]]$PDPlots) }
dev.off()

# Create table for run specifics, optTrees, and rsq_is
parms1 <-lapply(fMods, function(x) {
  modelCall = strsplit(x$run.name, split = " ")
  return(data.frame(resp = modelCall[[1]][1], 
                    covariate = modelCall[[1]][2], 
                    obs = modelCall[[1]][3],
                    optTrees = x$optTrees,
                    rsq_is = round(x$rsq_is,2), 
                    stringsAsFactors = FALSE))
}) %>%
  do.call(rbind, .)


# Create mse table
parms2 <- ldply(lapply(X = fMods, "[", "mse"), data.frame) %>% # mse into df
  mutate(resp = rep(parms1$resp, each = 2), # add unique id
         obs = rep(parms1$obs, each = 2),
         covariate = rep(parms1$covariate, each =2),
         mse.mse_value = round(mse.mse_value, 3)) %>%
  melt(.) %>%
  dcast(resp + obs + covariate ~ mse.msetype) %>%
  mutate(obs.cov = paste(obs, covariate, sep ="")) # needed for plotting below

# Merge tables
parmsTable <- merge(parms1, parms2)

write.table(x = parmsTable, file = "ohio2016/output/allGbmTable.txt", row.names = FALSE)

# Plot of osMSE values
ggplot(parmsTable, aes(obs.cov, out_sample)) +
  geom_bar(stat = "identity") +
  facet_wrap(~resp, scale = "free_y")

# Plot of is_rsq values
ggplot(parmsTable, aes(obs.cov, rsq_is)) +
  geom_bar(stat = "identity") +
  facet_wrap(~resp, scale = "free_y")
